### ISSUE TITLE
error in Npm start (Demo)

### ISSUE THREAD

**Issue by javatechy** [atlassian/browser-interaction-time#57]
Getting this error while running `npm start` in demo

```
D:\experiments\browser-interaction-time\demo\node_modules\clean-webpack-plugin\dist\clean-webpack-plugin.js:17
      throw new Error(`clean-webpack-plugin only accepts an options object. See:
      ^

Error: clean-webpack-plugin only accepts an options object. See:
            https://github.com/johnagan/clean-webpack-plugin#options-and-defaults-optional
    at new CleanWebpackPlugin (D:\experiments\browser-interaction-time\demo\node_modules\clean-webpack-plugin\dist\clean-webpack-plugin.js:17:13)
    at Object.<anonymous> (D:\experiments\browser-interaction-time\demo\webpack\webpack.common.js:21:5)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (D:\experiments\browser-interaction-time\demo\webpack\webpack.config.dev.js:4:16)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! browser-interaction-time-demo@1.0.0 start: `webpack-dev-server --open --config webpack/webpack.config.dev.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the browser-interaction-time-demo@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\deekumar\AppData\Roaming\npm-cache\_logs\2019-05-03T08_41_07_042Z-debug.log
```

**Comment by meandmax** [comment]
CI did not catch that this greenkeeper update breaks the demo and I did not know that greenkeeper updates also packages in sub-directories: https://github.com/atlassian/browser-interaction-time/pull/59

works now again :)

**Comment by meandmax** [comment]
Thanks for reporting this error: I added an issue to also run the demo in the tests. https://github.com/atlassian/browser-interaction-time/issues/60
